---
title: "tmp_map"
author: "LimnoTech"
date: "August 2, 2018"
output: html_document
---

```{r load, include = TRUE, cache = TRUE, eval = TRUE, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Libraries ------------------
library(leaflet)
library(htmltools)
library(bcmaps)
library(sf)
library(dplyr)

# Functions ------------------

# Icons ----------------------

#source files ----------------
load("out/data/pm_stats.RData")
load("out/data/airzone_map.RData")
load("out/data/airzones_annual_mgmt.RData")

# Data prep ------------------
# filter for relevant stations. Will add logical later to allow for toggle between 24-h and annual results
pm_stats_sub <- pm_stats %>% filter(metric == "pm2.5_annual")

# Used to conditionally apply color to awesome icons
get_color <- function(pm_stats_sub) {
  sapply(pm_stats_sub$metric_value, function(metric_value) {
    if(metric_value <= 4) {
      "#F0F0F0"
    } else if (metric_value > 4 && metric_value <= 6.4) {
      "#BDBDBD"
    } else if (metric_value > 6.4 && metric_value <= 10) {
      "#737373"
    } else {
      "#252525"
    }
  })
}

icons <- awesomeIcons(
  icon = "ios-close"
  , iconColor = "white"
  , library = "ion"
  , markerColor = get_color(pm_stats_sub)
)

# Identify unique airzones
az <- unique(airzone_map$Airzone) %>% data.frame(Airzone = ., stringsAsFactors = F)

# summarise stations in each airzone for labeling
airzone_summary <- pm_stats_sub %>% 
  group_by(Airzone) %>% 
  summarise(station_ct = n())

# Ensure all 7 airzones are present
airzone_summary <- left_join(az, airzone_summary)
airzone_summary$station_ct[is.na(airzone_summary$station_ct)] <- 0

airzone_map <- left_join(airzone_map, airzone_summary[ , c(1:2)])
airzone_map <- left_join(airzone_map, airzones_annual_mgmt[ , c(1, 6)])
airzone_map$caaqs_annual[is.na(airzone_map$caaqs_annual)] <- levels(airzone_map$caaqs_annual)[1]

# Create a dataframe without spatial properties for labeling
df_lab <- airzone_map
st_geometry(df_lab) <- NULL

## Used to generate multi-line labels for airzone polygons
labs <- lapply(seq(nrow(df_lab)), function(i) {
  paste0('<p>', data.frame(df_lab[i, "Airzone"]), "</p><p>" , df_lab[i, "station_ct"], " Monitoring Stations", "</p>")
})

```

```{r setup, include = TRUE, eval = TRUE, echo=FALSE, message=FALSE, warning=FALSE}

# Libraries ------------------
library(leaflet)
library(htmltools)
library(bcmaps)
library(sf)
library(dplyr)

# Mapping -------------
# create base map and fit to BC bounding box
m <- 
  leaflet() %>%
  addProviderTiles(leaflet::providers$CartoDB.Positron) %>%  # Add default OpenStreetMap map tiles, CartoDB.Positron
  fitBounds(-139.06, 48.30, -114.03, 60.0)

# add airzones and labels
bin_az <- c(levels(airzone_map$caaqs_annual))
pal_az <-  colorFactor(c('#73A5CD', '#DBDBDB', '#CD7378'), domain = bin_az)

m <- 
  m %>% 
  addPolygons(data = airzone_map, weight = 3, color = 'white'
              , fillColor = ~pal_az(caaqs_annual), fillOpacity = 0.75, label = lapply(labs, HTML))

# add airzone stations
m <-
  m %>% 
  addAwesomeMarkers(m, lng = pm_stats_sub$longitude, lat = pm_stats_sub$latitude, label = as.factor(pm_stats_sub$station_name), icon = icons, popup =
               paste("<font size = '+2'>Station: ", pm_stats_sub$station_name, "</font><hr>"
                             , "Air Zone: ", pm_stats_sub$Airzone, "<br>"))
  # # addMarkers(m, lng = pm_stats_sub$longitude, lat = pm_stats_sub$latitude, label = as.factor(pm_stats_sub$station_name)
  #            , popup =
  #              paste("<font size = '+2'>Station: ", pm_stats_sub$station_name, "</font><hr>"
  #                            , "Air Zone: ", pm_stats_sub$Airzone, "<br>"))

m

```

